import type { Quiz } from "@/app/quiz/page";
import jsPDF from "jspdf";

export function generateQuizPDF(quiz: Quiz) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Colors
  const primaryColor = [30, 232, 118] as const; // #1ee876
  const textColor = [30, 30, 30] as const;
  const mutedColor = [100, 100, 100] as const;

  // Header with logo area
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, pageWidth, 35, "F");

  // Title
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("Pogo", margin, 22);

  // Quiz title
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(quiz.title, pageWidth - margin, 22, { align: "right" });

  y = 50;

  // Quiz info bar
  doc.setFillColor(245, 245, 245);
  doc.rect(margin, y, contentWidth, 15, "F");
  doc.setTextColor(...mutedColor);
  doc.setFontSize(10);
  doc.text(`${quiz.questions.length} Questions`, margin + 5, y + 10);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - margin - 5, y + 10, { align: "right" });

  y += 30;

  // Name field
  doc.setTextColor(...textColor);
  doc.setFontSize(11);
  doc.text("Name: ", margin, y);
  doc.setDrawColor(200, 200, 200);
  doc.line(margin + 20, y, margin + 100, y);

  doc.text("Date: ", pageWidth - margin - 60, y);
  doc.line(pageWidth - margin - 40, y, pageWidth - margin, y);

  y += 15;

  // Divider
  doc.setDrawColor(...primaryColor);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);

  y += 15;

  // Questions
  quiz.questions.forEach((question, index) => {
    // Check if we need a new page
    if (y > 250) {
      doc.addPage();
      y = margin;
    }

    // Question number badge
    doc.setFillColor(...primaryColor);
    doc.roundedRect(margin, y - 5, 10, 10, 2, 2, "F");
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(`${index + 1}`, margin + 5, y + 2, { align: "center" });

    // Question type badge
    const typeLabel = question.type.replace("-", " ").toUpperCase();
    doc.setFillColor(240, 240, 240);
    doc.roundedRect(margin + 15, y - 5, 30, 10, 2, 2, "F");
    doc.setTextColor(...mutedColor);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.text(typeLabel, margin + 30, y + 2, { align: "center" });

    y += 12;

    // Question text
    doc.setTextColor(...textColor);
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");

    const questionLines = doc.splitTextToSize(question.question, contentWidth - 10);
    doc.text(questionLines, margin + 5, y);
    y += questionLines.length * 6 + 5;

    // Options
    if (question.options) {
      question.options.forEach((option, i) => {
        const letter = String.fromCharCode(65 + i);

        // Option circle
        doc.setDrawColor(200, 200, 200);
        doc.setLineWidth(0.3);
        doc.circle(margin + 10, y - 1.5, 3, "S");

        // Option letter
        doc.setTextColor(...mutedColor);
        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.text(letter, margin + 10, y, { align: "center" });

        // Option text
        doc.setTextColor(...textColor);
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        const optionLines = doc.splitTextToSize(option, contentWidth - 25);
        doc.text(optionLines, margin + 20, y);
        y += optionLines.length * 5 + 4;
      });
    } else if (question.type === "short-answer") {
      // Answer lines for short answer
      doc.setDrawColor(220, 220, 220);
      doc.setLineWidth(0.2);
      for (let i = 0; i < 3; i++) {
        doc.line(margin + 5, y + i * 10, pageWidth - margin - 5, y + i * 10);
      }
      y += 35;
    }

    y += 10;
  });

  // Footer
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...mutedColor);
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
    doc.text(
      "Generated by Pogo",
      pageWidth - margin,
      doc.internal.pageSize.getHeight() - 10,
      { align: "right" }
    );
  }

  // Save the PDF
  doc.save(`${quiz.title.replace(/[^a-z0-9]/gi, "_")}_student.pdf`);
}

export function generateTeacherPDF(quiz: Quiz) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Colors
  const primaryColor = [30, 232, 118] as const;
  const textColor = [30, 30, 30] as const;
  const mutedColor = [100, 100, 100] as const;
  const correctColor = [34, 197, 94] as const;

  // Header
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, pageWidth, 35, "F");

  doc.setTextColor(30, 30, 30);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("Pogo", margin, 22);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`${quiz.title} (Teacher Copy)`, pageWidth - margin, 22, { align: "right" });

  y = 50;

  // Quiz info
  doc.setFillColor(245, 245, 245);
  doc.rect(margin, y, contentWidth, 15, "F");
  doc.setTextColor(...mutedColor);
  doc.setFontSize(10);
  doc.text(`${quiz.questions.length} Questions - ANSWER KEY INCLUDED`, margin + 5, y + 10);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - margin - 5, y + 10, { align: "right" });

  y += 30;

  // Name field
  doc.setTextColor(...textColor);
  doc.setFontSize(11);
  doc.text("Name: ", margin, y);
  doc.setDrawColor(200, 200, 200);
  doc.line(margin + 20, y, margin + 100, y);
  doc.text("Date: ", pageWidth - margin - 60, y);
  doc.line(pageWidth - margin - 40, y, pageWidth - margin, y);

  y += 15;

  doc.setDrawColor(...primaryColor);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);

  y += 15;

  // Questions with answers
  quiz.questions.forEach((question, index) => {
    if (y > 230) {
      doc.addPage();
      y = margin;
    }

    // Question number
    doc.setFillColor(...primaryColor);
    doc.roundedRect(margin, y - 5, 10, 10, 2, 2, "F");
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(`${index + 1}`, margin + 5, y + 2, { align: "center" });

    // Type badge
    const typeLabel = question.type.replace("-", " ").toUpperCase();
    doc.setFillColor(240, 240, 240);
    doc.roundedRect(margin + 15, y - 5, 30, 10, 2, 2, "F");
    doc.setTextColor(...mutedColor);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.text(typeLabel, margin + 30, y + 2, { align: "center" });

    y += 12;

    // Question text
    doc.setTextColor(...textColor);
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    const questionLines = doc.splitTextToSize(question.question, contentWidth - 10);
    doc.text(questionLines, margin + 5, y);
    y += questionLines.length * 6 + 5;

    // Options with correct answer highlighted
    if (question.options) {
      question.options.forEach((option, i) => {
        const letter = String.fromCharCode(65 + i);
        const isCorrect = option === question.correctAnswer;

        if (isCorrect) {
          doc.setFillColor(220, 252, 231);
          doc.roundedRect(margin + 5, y - 5, contentWidth - 10, 10, 2, 2, "F");
        }

        doc.setDrawColor(isCorrect ? 34 : 200, isCorrect ? 197 : 200, isCorrect ? 94 : 200);
        doc.setLineWidth(isCorrect ? 0.5 : 0.3);
        doc.circle(margin + 10, y - 1.5, 3, isCorrect ? "FD" : "S");

        if (isCorrect) {
          doc.setFillColor(...correctColor);
          doc.circle(margin + 10, y - 1.5, 1.5, "F");
        }

        doc.setTextColor(isCorrect ? 34 : 100, isCorrect ? 197 : 100, isCorrect ? 94 : 100);
        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.text(letter, margin + 10, y, { align: "center" });

        doc.setTextColor(isCorrect ? 34 : 30, isCorrect ? 197 : 30, isCorrect ? 94 : 30);
        doc.setFontSize(10);
        doc.setFont("helvetica", isCorrect ? "bold" : "normal");
        const optionLines = doc.splitTextToSize(option, contentWidth - 25);
        doc.text(optionLines, margin + 20, y);
        y += optionLines.length * 5 + 4;
      });
    } else if (question.type === "short-answer") {
      // Show correct answer for short answer
      doc.setFillColor(220, 252, 231);
      doc.roundedRect(margin + 5, y - 3, contentWidth - 10, 20, 2, 2, "F");
      doc.setTextColor(...correctColor);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.text("ANSWER:", margin + 10, y + 4);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...textColor);
      const answerLines = doc.splitTextToSize(question.correctAnswer, contentWidth - 30);
      doc.text(answerLines, margin + 10, y + 12);
      y += 25;
    }

    y += 10;
  });

  // Footer
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...mutedColor);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });
    doc.text("Generated by Pogo - TEACHER COPY", pageWidth - margin, doc.internal.pageSize.getHeight() - 10, { align: "right" });
  }

  doc.save(`${quiz.title.replace(/[^a-z0-9]/gi, "_")}_teacher.pdf`);
}

export function generateAnswerKeyPDF(quiz: Quiz) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Colors
  const primaryColor = [30, 232, 118] as const;
  const textColor = [30, 30, 30] as const;
  const mutedColor = [100, 100, 100] as const;

  // Header
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, pageWidth, 35, "F");

  doc.setTextColor(30, 30, 30);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("Pogo", margin, 22);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Answer Key", pageWidth - margin, 22, { align: "right" });

  y = 50;

  // Quiz title
  doc.setTextColor(...textColor);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(quiz.title, margin, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...mutedColor);
  doc.text(`${quiz.questions.length} Questions | Generated: ${new Date().toLocaleDateString()}`, margin, y);
  y += 15;

  doc.setDrawColor(...primaryColor);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 15;

  // Answer key grid
  quiz.questions.forEach((question, index) => {
    if (y > 270) {
      doc.addPage();
      y = margin;
    }

    // Question number
    doc.setTextColor(...textColor);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(`${index + 1}.`, margin, y);

    // Question type
    doc.setTextColor(...mutedColor);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    const typeLabel = `(${question.type.replace("-", " ")})`;
    doc.text(typeLabel, margin + 10, y);

    // Answer
    doc.setTextColor(...primaryColor);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    
    let answerText = question.correctAnswer;
    if (question.options) {
      const answerIndex = question.options.indexOf(question.correctAnswer);
      if (answerIndex !== -1) {
        answerText = `${String.fromCharCode(65 + answerIndex)}. ${question.correctAnswer}`;
      }
    }
    
    const answerLines = doc.splitTextToSize(answerText, contentWidth - 50);
    doc.text(answerLines, margin + 45, y);
    y += answerLines.length * 6 + 6;
  });

  // Footer
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...mutedColor);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });
    doc.text("Generated by Pogo - ANSWER KEY", pageWidth - margin, doc.internal.pageSize.getHeight() - 10, { align: "right" });
  }

  doc.save(`${quiz.title.replace(/[^a-z0-9]/gi, "_")}_answer_key.pdf`);
}
